jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.5
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - run: |
          bundle install
      - run: |
          bundle exec rake test
